version: '3'
services:
  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  nzxt-docs:
    image: ghcr.io/naoki-tomita/nzxt-docs:latest
    environment:
      - PORT=80
