version: '3'
services:
  load-balancer:
    image: nginx:1.23.0
    volumes:
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/log/nginx:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
    command: "/bin/sh -c 'while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot:
    # you should use if oracle cloud infrastructure arm64 cpu.
    #image: certbot/certbot:arm64v8-latest
    image: certbot/certbot:v1.29.0
    volumes:
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
      - ./log_letsencrypt:/var/log/letsencrypt
    # you should comment out when first time.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
  nzxt-docs:
    image: ghcr.io/naoki-tomita/nzxt-docs:latest
    environment:
      - PORT=80
